
modid = hyperbox
mod_version = 6.0.0.1
mc_version = 1.21.3
neo_version = 21.3.11-beta
infiniverse_mc_version = infiniverse-1.21.3
infiniverse_version = 2.1.0.0
infiniverse_min_version = 2.1.0.0
infiniverse_max_version = 2.2.0.0
exmachina_mc_version = exmachina-1.21.3
exmachina_version = 0.8.0.2-beta
exmachina_min_version = 0.8.0.2-beta
exmachina_max_version = 0.9.0.0
